name: MC_QQ
version: 2.6.0
main: com.github.theword.MCQQ
api-version: 1.14
authors: [ 17TheWord ]
description: 基于NoneBot的与Minecraft Server互通消息的插件
website: https://github.com/17TheWord/MC_QQ_Spigot
commands:
  mcqq:
    description: MCQQ命令
    permission: mcqq
    permission-message: 您没有执行命令的权限
