name: MC_QQ
version: 2.5.1
main: com.github.theword.MC_QQ
api-version: 1.12.2
authors: [ 17TheWord ]
description: 基于NoneBot的与Minecraft Server互通消息的插件
website: https://github.com/17TheWord/nonebot-plugin-mcqq
